### ISSUE TITLE
-mm mode or remove entirely

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#1]
Remove default mirror mode > all players can pick the same champion.
Make mode with command at start of game maybe to activate it. -mm.

**Comment by FlyOutBoy** [comment]
https://drive.google.com/file/d/17KpAXMrSxFSoZDhhAL4i7bumoidEIcmH/view?usp=sharing
needs to check it, activated by command "-mm" if first seconds

**Comment by FlyOutBoy** [comment]
done
