### ISSUE TITLE
Ulqiorra W adjustment

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#13]
Ulqiorra W - change can't use under 30% hp > Can't activate under 30% hp
+ edit tooltip

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
It does what I asked BUT it still eats the mana the way it is now. So.. it's still bugged xD

I was thinking more like this man. 'Requires: 30% of HP or more' as in the example of Ichigo's ult. I mentioned this before on discord about Ichigo's ult.
![image](https://user-images.githubusercontent.com/110841373/185767821-0ffb0fee-f60f-4d2b-881b-09571aa76b4c.png)

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185804579-94267359-8c0c-48d8-9d9a-979c49b299a0.png)
done
