### ISSUE TITLE
Abilities UI placement bug *(floating bug?)

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#17]
Fix abilities UI placement bug. Sometimes abilities will be in the wrong slot.  Happens randomly on random heroes and often times the next game it will be ok even if same hero is used.

**Comment by FlyOutBoy** [comment]
Its a default WC3 bug, if u learn ability in random turn , then they would place random place till you dont learn all level abilities, example : ( first screen it this situation, second the same ,but when u learn all abilities for full all of them take them place, p.s. its cant be fixed)

![image](https://user-images.githubusercontent.com/33839947/185749823-1d365b90-7531-4896-856a-789a9b4d1d4f.png)
![image](https://user-images.githubusercontent.com/33839947/185749837-a34ade72-f41f-47fd-91a4-343af4894a0d.png)

**Comment by tpdjairks** [comment]
What do you mean??

I play war3 since 2006. It's not WC3 bug, If it was WC3 bug it would work like this in all the maps.
![image](https://user-images.githubusercontent.com/110841373/185768079-46aa7313-ba28-4e68-8ea0-bb7eecf071f3.png)

'WC3 bug' <.< This is old map, Why it's not the same if it's WC3 bug as you say?  It's obviously map bug not WC3 bug.

**Comment by FlyOutBoy** [comment]
call me lifehacker 
![image](https://user-images.githubusercontent.com/33839947/185805182-a3b7f4bd-6254-42ad-a5dc-65f69c740efd.png)
