### ISSUE TITLE
Renji Q and R bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#18]
Projectile shoots in the opposite direction than it should on both abilities.
#21 can maybe use the 2,08b map to fix those.

**Comment by FlyOutBoy** [comment]
But there even havent any projectile
![image](https://user-images.githubusercontent.com/33839947/185691735-2db5e1a2-bc7e-4bf1-9683-2f98aa7e6041.png)
![image](https://user-images.githubusercontent.com/33839947/185691775-a059bdf2-0ecd-45be-9f1a-73e4ba7c47dd.png)
everything good there

**Comment by tpdjairks** [comment]
Ok, I meant, the spell shoots in the opposite direction.
It's not good xD

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/185753352-bf29b5cd-03d9-42ec-a5ed-388565850952.png)
It needs to hit with the spikes of the sword not with the other side, wtf? xD
And it's same for R. 

It's like he twists his arms like a cyborg to that attack lol.

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/185753887-63395a6a-807c-4a31-acaa-6256ef9b6fac.png)
And this needs to shoot clockwise not counterclockwise.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185756379-d25448b1-9f5c-4e82-bdef-517350c465b1.png)
fixed
