### ISSUE TITLE
Only 1 type of miniboss bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#2]
Only Blade Master*(Axe hero model in DotA) spawns as mini boss*(The top corner portal subs 'Ancients') 
Normally there's more Ancients spawning not just one type.

#21 can maybe use 2.08b to fix.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185695389-a16ebdf8-02a8-4e67-be96-0b0f3b0c2a0e.png)
done
