### ISSUE TITLE
Secret heroes

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#20]
Check if Sasuke and Squall are still 'secret heroes'. Delete Squall Lionheart and make Sasuke Uchiha available in the taverns if yes.

**Comment by FlyOutBoy** [comment]
They haven't any abilities, also no icon, sounds etc

**Comment by tpdjairks** [comment]
[Bleach vs One Piece v2.26c.zip](https://github.com/FlyOutBoy/BvO-Another/files/9384754/Bleach.vs.One.Piece.v2.26c.zip)
Can you import Sasuke from this map maybe?

If yes make him keep his [V] blink in his [R] form.
In that map he got Shunpo but when he transforms he has his old V with miss chance passive and no blink anymore.
So make his R transformation give evasion and let him have Shunpo[V] active during his R instead of Evasion[V] passive.

**Comment by FlyOutBoy** [comment]
Its cant be improted because too awful code ( random funcs and abilities name with same name on other abils, + it gui convert, so there are more sense make it byself
