### ISSUE TITLE
Restore Brook hero

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#21]
Restore him if possible

**Comment by FlyOutBoy** [comment]
Brook has not any spells , he need to do every ability

**Comment by tpdjairks** [comment]
Port from this map lol. It's open map. Only has 1 bug as far as I know; transparent Ichigo lol. Maybe you can use that bug for that new boots lmao xD

[Bleach vs One Piece v2.08b.zip](https://github.com/FlyOutBoy/BvO-Another/files/9355579/Bleach.vs.One.Piece.v2.08b.zip)

P.S.: fix Brook [R] camera reset after skill end bug if you port him.

**Comment by FlyOutBoy** [comment]
Awful code , cant be imported
