### ISSUE TITLE
Zoro W bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#26]
Zorro W AoE bug - the backwards waves deal damage to enemies in the front as well. I think the AoE is bugged. They should not reach that far. It deals 2x damage basically. High priority fix. 

#21 just use the old one. That one it's well adjusted already for [V]+[W] combo.

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
1.1a Damage dealt with lvl 2 W
![image](https://user-images.githubusercontent.com/110841373/185769501-e4f835f1-9d34-422c-8526-b96aba34cf14.png)

1.1c Damage dealt with Lvl 2 W
![image](https://user-images.githubusercontent.com/110841373/185769406-f2dc3d14-37b6-4efa-b63e-2e08e5a29b62.png)

Yeah that seems just about right.
