### ISSUE TITLE
Make passives originating from itms to be 'unique'

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#27]
Prevent passives from itms stacking with themselves.

Hell Crusher - stun passive.
Killer Axe - ministun passive.
Suzumebachi - crit chance.
Sokyoku - crit chance.
Ultima Sword - crit chance + ministun.
Zanbato - cleave effect.
Sentomaru's Axe - cleave effect.

This should only apply to effects coming from the exactly same type of item.

**Comment by FlyOutBoy** [comment]
Make ban for taking one more of this items in slot, also added katen kyokotsu
