### ISSUE TITLE
Grammar fix for Lvl medals

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#29]
Fix grammar for new lvl up medals when you try to buy but don't have enough medals/lumber 'Your need 7/8/9 medals for purchase' > 'You need 7/8/9 medals to purchase'.

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
Half done xD 
![image](https://user-images.githubusercontent.com/110841373/185768540-8ac0b9c8-0d27-48de-8706-b641b8e8c826.png)

'Your' > 'You'.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185790044-2d5ab45c-23fb-45c8-9bf6-e6eb5ed46f9a.png)
done
