### ISSUE TITLE
Switch Nami E clones spell to Manta Style type ability

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#3]
Nami E bug - 1 of the 4 clones dissapears soon after casting E.  
Also switch her E skill to Manta Style's active where she dissapears for a moment. It's much better to confuse the enemies than just make clones appear next to hero. Same stats clones.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185698058-6c56cf67-c7d0-4a25-819e-687dc7bedd1f.png)
done, she has invulnerability for 0.35 sec also gain 100% transparent for this time, after create illsuion

**Comment by tpdjairks** [comment]
Not what I had in mind but alright, I'll take it.

BUT

1 of 4 clones is still disappearing. Super weird bug, if in base it works fine. 
![image](https://user-images.githubusercontent.com/110841373/185767247-83454213-939e-4914-a36a-e28ec5675682.png)

Outside of base, exit to mid portal or anywhere else and it's bugged.
![image](https://user-images.githubusercontent.com/110841373/185767117-cc65b873-34af-4480-95ae-ca2205e4686c.png)

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185805573-ee536604-32c1-4298-a829-f592d0cc8047.png)
Idk, ,make 1 more debug, but i think everything good
