### ISSUE TITLE
Update Atlas icons

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#30]
Lvl. 1 icon -https://www.hiveworkshop.com/threads/book-with-earth-nature-spells.318330/
Lvl. 2 icon -https://www.hiveworkshop.com/threads/book-with-wind-spells.318334/
Lvl. 3 icon -https://www.hiveworkshop.com/threads/book-with-fire-spells.318331/

**Comment by FlyOutBoy** [comment]
done
