### ISSUE TITLE
Reiatsu boots rework

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#36]
New Icon:https://www.hiveworkshop.com/threads/btn-boots3.57366/

New Build: Shihoin's boots + Armor ring + Reiatsu Orb + recipe (1550)

New Stats: +65 movement speed, +20% attack speed +5 All stats, +3 Armor, +250 Mana.

New Active: Repelnish 250 Mana in 700 AoE

**Comment by FlyOutBoy** [comment]
i think you mean reiatsu booster, not orb

**Comment by FlyOutBoy** [comment]
Also there ring or protection not armor

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185809798-d20070e3-8faf-45ae-b8c7-5f51845fef7e.png)
![image](https://user-images.githubusercontent.com/33839947/185809805-d3421344-2e39-497d-9880-d4b338d68e1f.png)
done
