### ISSUE TITLE
Add mana bars

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#37]
https://www.hiveworkshop.com/threads/vjass-heath-mana-bar-system-v2-1.241348/

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185749122-924d5de6-34ac-4d16-a7b9-f3c4b0344bfb.png)
![image](https://user-images.githubusercontent.com/33839947/185749135-7decca75-248a-476d-a299-329bc657e3ee.png)
done, this system cant be scalled properly
