### ISSUE TITLE
Investigate jump flash abilities

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#39]
Ichigo R *(black Ichigo)
Yoruichi E
Yamamoto E,
Zangetsu ult, 

Investigate the code for all ability levels. Either I'm blind either sometimes they jump -1 than the tooltip says. They seem to work correctly for ability lvl 5 from what I could tell just ability lvl 1 - 4 will sometimes have issues.

If nothing seems to be wrong with the code do nothing.

**Comment by FlyOutBoy** [comment]
everything good with it, test every skill dont see any trouble

**Comment by tpdjairks** [comment]
Yeah idk, to me it seemed that only lvl 5 abilities work correctly as the tooltips says it does but alright, This one is whatever to begin with. I just thought maybe there was something wrong with the code.
