### ISSUE TITLE
Fix Ichigo going into Vasto Lorde and back reseting itms cooldown.

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#40]
Attached rossoliny's source files just in case. His fix has a different bug though, Ichigo will lose his itms when Vasto Lorde ends.
 
[bvo-another--1 (1).zip](https://github.com/FlyOutBoy/BvO-Another/files/9355000/bvo-another--1.1.zip)

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185904919-cbb447a4-75ec-4f44-8610-620ff3208dde.png)
Fixed
