### ISSUE TITLE
Fix Orihime's passive Orb effect + Katen's*(and Drake Axe) Orb effect

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#45]
She does the attack animation but nothing comes out. She's just 'punching in the air'.

Make similar triggers to Mace of Zeus itm maybe if can't fix another way.

It's not a big deal, we usually buy Life Steal itm and it'll 'fix' itself lol. But it'd be a quality of life improvement for Orihime. We build Katen for the MS buff.

**Comment by FlyOutBoy** [comment]
Done, katen kyokotsu and drakens axe will not work with his passive abilities on her , but orihime gain all other effects from this items
