### ISSUE TITLE
Byakuya R visual bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#48]
The cage is only visible from within, it's invisible from outside. 

It doesn't work like that in the anime as far as I'm aware so I think it should be fixed even if hypothetically Unryze meant it to be a feature maybe, although I doubt it.

**Comment by FlyOutBoy** [comment]
Delete fogged attibute in effect, so its can be visible some longer , but if u put camera on 1 small part on senkei its dissapear, bcs, its model 
![Uploading image.png…]()

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/185860894-daa3068d-c29a-4214-9d29-c6f4a8c75f3e.png)
At least add some terrain modifier or other visible effect to it like it was in older version. Doesn't have to be like this but just something to let people know he used his R lol.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185933943-e9cc64d2-5b87-4252-8921-eab1bae114cc.png)
