### ISSUE TITLE
Rukia E bug *(floating bug?)

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#5]
Rukia E bug - sometimes passes through units and deals no dmg or stun. But it's very stange that not always. Some games works fine. Maybe it's related to icons switch places bug.

**Comment by FlyOutBoy** [comment]
Make some bigger aoe spell, test 20 more casts and everythings good

**Comment by tpdjairks** [comment]
Yes, it's very weird. I think it's about game loading.
Sometimes it loads 'wrong' and then it's bugged. Or I don't know but it's super random stuff and other times it works just fine.

I think if you fix the bug with Icons switching places it'll be ok after. 

Try to level abilities out of order, instead of Q W E R do R E W Q for example then this bug will happen more maybe.
