### ISSUE TITLE
Hitsugaya E model - nerf the wings size

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#50]
Hitsugaya E - The bankai wings are a bit oversized, this was intended by Unryze I guess but he overdid it, try to make them smaller or revert to old version.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185480449-901e25c2-cdde-47c2-9517-54484be86aa7.png)
Done

**Comment by tpdjairks** [comment]
Perfect, He was taking too much screen space with those new wings lol.
