### ISSUE TITLE
Tosen E burn rebalance 

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#53]
Deals dmg each 0.7 seconds over 4.9 seconds (7 times) 

Lvl 1 - 1% Max Hp + 10% Current Hp.
Lvl 2 - 2% Max Hp + 10% Current Hp.
Lvl 3 - 3% Max Hp + 10% Current Hp.
Lvl 4 - 4% Max Hp + 10% Current Hp.
Lvl 5 - 5% Max hp + 10% Current Hp.

**Comment by FlyOutBoy** [comment]
Its total dmg or per sec?

**Comment by FlyOutBoy** [comment]
Done
