### ISSUE TITLE
Make gold coins clickable on top of units

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#54]
Some people will use hacks to achieve this I remember, creating an unfair advantage for those who don't. So make it a feature instead and let everyone have it.

**Comment by FlyOutBoy** [comment]
I even dont see that, but such way it cant be maked by map code, there's idea to add this info to multiboard or etc

**Comment by tpdjairks** [comment]
How about flying gold coins? xDD

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185941141-389d45c6-4cde-4db4-9042-d7c60081646a.png)
make bigger aoe of taken coins 2x, start of area to clicking coin showed on cursor
