### ISSUE TITLE
Lucci CP9 nerf

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#55]
E nerf - nerf max knockback damage 150-800 > 150-500
W nerf -  make the tiger form [W] to trigger Darkness Sphere passive spell block, the same as his normal form W does. 

Currently his Tiger form [W] can't be blocked with Sphere's passive and he's the only hero in the entire game to have a targeted stun that doesn't trigger the Sphere block. It always annoyed me a little that I could not build Sphere vs him.

**Comment by FlyOutBoy** [comment]
E nerfed
2) With Dark Sphere troubles its not blocking any targets, only controls like Stun, Slow etc, maybe its broken when added or something else

**Comment by tpdjairks** [comment]
Well yeah I made a sperate issue about Sphere not working.

But I mean, once that is fixed, pls change his tiger form W to trigger the sphere and not to get stunned by it. In old versions his tiger W did not trigger sphere.
