### ISSUE TITLE
Hitsugaya buff

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#65]
Base int 20 > 25.
[R] CD 70 > 70/65/60/55/50

**Comment by FlyOutBoy** [comment]
Complete

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/185768750-a971e88b-ab93-4e55-988f-d299787faa9f.png)
I forgot to add documentation tag e.e my bad.

**Comment by FlyOutBoy** [comment]
fixed description
