### ISSUE TITLE
Revert Nico Robin [V] to 2,08b version

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#66]
See #21

**Comment by FlyOutBoy** [comment]
done

**Comment by tpdjairks** [comment]
Almost done xD

Needs to be invulnerable during flight and untargetable too I think,

And she drops down too quickly. Needs to stay in the air +1 second than current value. I think now it's 1 seconds flight, needs to be 2 seconds flight.

**Comment by FlyOutBoy** [comment]
0.75 sec >1.95 sec, also added Invulnerability for fly

**Comment by tpdjairks** [comment]
Ok but. Flash jump abilities need to not aggro onto her.  I will test this and let you know.

And if 0.75 sec then > 1.5 sec should be the right amount I think.
