### ISSUE TITLE
Fix only 1 Ai picking 

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#67]
After 18 august map only 1 Ai works.
![image](https://user-images.githubusercontent.com/110841373/185720870-eac90666-a13d-4794-b7fd-cf5ee7ffe63a.png)

They're all open but only 1 Ai will pick.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185752208-98c7a151-b72f-450c-a273-e34f13114d62.png)
done
