### ISSUE TITLE
Team colors are gone <.<

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#68]
![image](https://user-images.githubusercontent.com/110841373/185722627-292d03d8-3834-4958-a6aa-fd029267453b.png)

I don't know if it's a bug or what but I did not request this change <.< 

Can't tell what team everyone is unless you look at minimap all the time. Each game need to re-adjust and learn and remember who is on your team.

This map had team colors before, blue ally, red enemy. Pls add it back.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185742950-b7a5fe69-c832-4d0a-9a15-89167d760b65.png)
you should change this

**Comment by tpdjairks** [comment]
Yes, That's what I'm saying. It does not work. Something broke. Now it only shows colors on minimap. Team color auras are gone.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/185756510-bfb8ec3a-0b42-41c2-a53f-f805341096b6.png)
???

**Comment by tpdjairks** [comment]
![image](https://user-images.githubusercontent.com/110841373/185764426-d8c40243-ea01-4622-894b-45ba5b693970.png)

Sorry, It wasn't anything you did. It was Unryze's doing it seems. But in any case it needs to be like that.

**Comment by FlyOutBoy** [comment]
This teamglow using in model only, so he delete it from every model, i try to add it with aura effect, but if model have troubles with attachments you cant see this aura
![image](https://user-images.githubusercontent.com/33839947/185791442-60a5ee90-92b4-4337-9f9b-d07653cd19e6.png)
![image](https://user-images.githubusercontent.com/33839947/185791954-a878a9e1-0e87-4ed4-8f1e-8c0ebaf3f62b.png)

**Comment by tpdjairks** [comment]
??? 



Red is for enemy. Light blue is for ally.  Blue for self.

**Comment by FlyOutBoy** [comment]
Fixed
