### ISSUE TITLE
Rukia can now learn E at lvl 1.

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#70]
![image](https://user-images.githubusercontent.com/110841373/185768186-191de788-b96a-476e-b2d3-10668ab42a45.png)
![image](https://user-images.githubusercontent.com/110841373/185768197-95e5fdd4-11ca-4d23-84e3-1c1bdac6f67e.png)

**Comment by FlyOutBoy** [comment]
Done
