### ISSUE TITLE
Sado and Mihawk ult works on creeps.

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#71]
Their ults should only work on heroes. And if you try to ult a creep it should be like this:
![image](https://user-images.githubusercontent.com/110841373/185769118-cf0b5b69-bdbb-468f-9f67-28fcab50a470.png)

Instead I can ult creeps with their ults. So make their ults be like all the other ults. If try to ult a creep it'll say 'Must target a Hero'.

**Comment by FlyOutBoy** [comment]
done
