### ISSUE TITLE
Sphere ministuns and exceptions

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#72]
Include:
- Katen and Drake's Axe Orb effect slow *(if didn't already)
- Mihawk Q maim effect
- Rob Luci tiger W stun *not working but human form W stun works
- Tosen Q Sleep
- Hitsugaya E AoE activation slow and W slows 
- Kuzan ult stun
- Hex + global Hex *(forgot to test it, ignore it if already included)
- Soul-devourer Stones red lightning 

Exclude:

- Renji E stun
- Luffy Q stun
- Rob Luci E knockback effect
- Tosen T silence
- Zangetsu R stun
- Zaraki E stun 
- Ishida W stun/ministun
- Rukia Q, W ,E. (Also, see #82  in case it's relevant) 
- Hitsugaya ult (Also see #90 in case it's relevant)
- Sado E stun (E 1st wave) 

Exclude all ministuns:

- Luffy E
- Crocodile W (After re-adding it. See #83) 
- Soi Fon Q passive on hit ministun
- Killer axe passive on hit ministun
- Ultima Sword passive on hit ministun
________________________________________________
Very important detail:
Stuns that are blocked should not cancel casting abilities.

**Comment by FlyOutBoy** [comment]
there's no activation slow in TOshiro E, there are aura slow that nonsense to disable, because it would affected in next few seconds

**Comment by FlyOutBoy** [comment]
Soul-devourer Stones red lightning cant be detected with trigger way

**Comment by FlyOutBoy** [comment]
done
