### ISSUE TITLE
Byakuya [W] animation bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#74]
His [W] needs to look like this and remain like this for the whole stun duration.
![image](https://user-images.githubusercontent.com/110841373/186016200-f3c82ab3-0fc2-45e7-b101-c796320a171b.png)
Currently it begins with the animation shown in the 1st picture above but then it switches and turns into a stun animation like shown in the 2nd picture below.
![image](https://user-images.githubusercontent.com/110841373/186016643-549abf3b-70ef-4b99-b8bd-7384590c6d2c.png)

**Comment by FlyOutBoy** [comment]
done, dont remove stun animation, because there are used ability with many stun levels , to avoid any troubles save it, but added animation of bakudo
![image](https://user-images.githubusercontent.com/33839947/186688389-3669a316-ff27-458b-a239-33de4b0082db.png)

**Comment by tpdjairks** [comment]
Why Scale 1.50 you madman? <.<
I'll nerf this lol.
