### ISSUE TITLE
Sentomaru's Axe old autocombine recipe still works

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#75]
Old recipe: "Perseverance + Broadsword + Jidanbo's Maul" => Updated Sentomaru's Axe.
New recipe "Perseverance + Jindabo's Maul + Gloves of Haste + gold recipe" => also Updated Sentomaru's Axe.

Remove old recipe autocombine => Sentomaru's Axe.

**Comment by FlyOutBoy** [comment]
Price for recipe?Stat change?

**Comment by tpdjairks** [comment]
> Price for recipe?Stat change?

![image](https://user-images.githubusercontent.com/110841373/186054806-71a5ae67-655b-470b-9cb4-afdecb184baa.png)

The stats are the new stats for both.

Problem is that both recipes work to make the same itm. Both old and new. And both recipes create the new itm.

**Comment by FlyOutBoy** [comment]
done
