### ISSUE TITLE
Add kill sound effects + duel song

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#76]
1. Add kill sound effects*(See zip file at the bottom) and increase the timer for being able to get multikills to 7 if it's currently lower than 7. It's hard to tell because I think it's bugged.
![image](https://user-images.githubusercontent.com/110841373/186053193-5032ef4b-631a-4e86-bf39-2cadb42dda8d.png)
2. ^And also remove these overlay texts once the sounds are added. They're bugged anyway and only show when YOU get double  etc. normally it should show for everyone not just for you (only tested it with bots though, maybe it works ok with players, then leave it if that's the case).

3. Add MK song file and make it start when timer reaches 0 right before duel and add command -duelmusic for ON/OFF. ON by default.
![image](https://user-images.githubusercontent.com/110841373/186053381-682220ec-badf-4007-b3fc-34691e36a904.png)
 
[Sound files.zip](https://github.com/FlyOutBoy/BvO-Another/files/9398735/Sound.files.zip)

**Comment by FlyOutBoy** [comment]
There's no need command, it can be just turn offed when u block music in wc3

**Comment by FlyOutBoy** [comment]
done
