### ISSUE TITLE
Itms rebalance

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#78]
Aleria's Sacred Sight rebalance + Tooltip edits
 
 +50 Damage > +75 Damage
 +30 Agility > +30% Attack Speed 
 +30% Ranged dmg buff*Unchanged   
______________________________________________
Totem of Might rebalance + Tooltip edits
 
 +100 Damage > +75 Damage
 +30% Attack speed *New
 +30% Melee dmg buff *Unchanged
______________________________________________
Sacrificial Wand rebalance + Tooltip edits

Recipe price 20000 gold > 10000 gold
+20 HP/second > 10 + 0.25% Max HP/ second
(Everything else unchanged)

Example for hp regen:
3000 HP => 10+ 7.5 HP/ second
6000 HP => 10+ 15 HP/ second
9000 HP => 10+ 22.5 HP/ second
etc.
______________________________________________
Hollow Shield rebalance + Tooltip edits

HP *unchanged
Regen *unchanged
65% chance to block 60 damage > 65% chance to block 60 damage non-hero damage
100% chance to block 60 hero damage *New
'Can't carry more than one' *New
______________________________________________
Zero Squad Armor price change + Tooltip edits

Recipe price 5000 gold > 8000 gold
______________________________________________
Maximilian 1 itm only + Tooltip

Unchanged
'Cant' carry more than one' *New
______________________________________________
Arrancar's Horn rebalance + Tooltip

Unchanged
New passive: Arrancar's Tenacity - When HP falls below 8% Max HP gain double the life steal and +60% Attack Speed buff for 3.5 seconds. No CD. Reset the timer if buff already exists when triggered.
______________________________________________
'Observation Haki' Active rebalance*(new green boots):

- Transparency Lvl1/Lvl2/Lvl3 - 100/95/90 *Change
- Duration Lvl1/Lvl2/Lvl3 - 3/3.5/4 seconds *Change
- +182 Movement speed buff for the duration *New
_____________________________________________

**Comment by FlyOutBoy** [comment]
in horn i make it 10% because even testing its too hard to check

**Comment by FlyOutBoy** [comment]
done
