### ISSUE TITLE
Hero ults can throw enemy out of map

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#79]
![image](https://user-images.githubusercontent.com/110841373/186233200-e4c8e3c1-e92c-4a81-ae02-96743f267e32.png)
If something can be done about it that would be nice.

Also,

'-unstuck ok' command doesn't even work anymore. So can't even use -unstuck command so pls add it back.

**Comment by FlyOutBoy** [comment]
make a command -unstuck with cd 60 sec, it drain your life about 75% of current life and after 15 second , make your height by 0 , set position to center arena, unpausing, clear debuffs, when delay active your unit in perma pause
