### ISSUE TITLE
Byakuya Q bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#81]
Byakuya Q is also 'invisible' from certain angels same as his R.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/186731750-e1b68600-7871-4060-9192-54085b3115d5.png)
done there's no bug, just to low effect on ability

**Comment by tpdjairks** [comment]
From certain angles it's invisible man. You can't see it cuz you're always in cast range when you shoot it but the enemy can. It's same as his R.
