### ISSUE TITLE
Crocodile W lost it's ministun

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#83]
Might be intended change by Unryze or maybe it's bugged. He used to apply ministun with his W. Add it back in any case.

**Comment by FlyOutBoy** [comment]
added 0.25 sec

**Comment by tpdjairks** [comment]
Idk about the code but in game it's more like 1-2 seconds. 

I love the animation btw.

**Comment by FlyOutBoy** [comment]
you have old vers
