### ISSUE TITLE
Kuzan visual bugs

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#88]
Remove stun effect animations from his E ability, his Q ability, his V ability, the end of his R ability and from his ult.

E shows stun animation as well as frozen animation but the frozen animation adds a slow. 
![image](https://user-images.githubusercontent.com/110841373/186264137-a01ea06b-bb3e-4e21-b7aa-3e745be71e46.png)
Q shows stun animation instead of frozen animation.
![image](https://user-images.githubusercontent.com/110841373/186264456-97d21a3c-b90f-4ca7-9ce1-972e6afffe8c.png)
R shows stun animation as well as frozen animation.
![image](https://user-images.githubusercontent.com/110841373/186265541-be289694-e028-431c-b9cd-050595b55c08.png)
V shows stun animation instead of frozen animation.
![image](https://user-images.githubusercontent.com/110841373/186265832-d0db7359-a34c-4a13-b6bc-59ceb583f912.png)

**Comment by FlyOutBoy** [comment]
done
