### ISSUE TITLE
Add Ishida W marker

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#9]
Ishida W - add marker *(I think Usopp E marker fits just fine for Ishida W).

**Comment by tpdjairks** [comment]
Also #21. Now that we have deprotected 2,08b pls check the [W] and compare to bvo another version. If AoE or anything dmg related it's any different pls revert to old numbers.

**Comment by FlyOutBoy** [comment]
It already was the same but 1 thing damage was physical, changed to magical, now it should be more stronger, btw from this version i cant extract anything i spend 30 mins to find only licht regen in restored code , changed marker
