### ISSUE TITLE
Ace R rebalance/ bug fix

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#91]
Bug:

His R fire balls can hit the same hero multiple time, it should only hit 1 hero 1 time even no other target. Make it 1 max fire ball per hero in any circumstances.

Other:
Try to rework this portion of his R where the fire balls simply freeze for a time and just sit there and make it a more fluid animation if possible.
![image](https://user-images.githubusercontent.com/110841373/186270498-4ca69325-6d29-443c-b12b-baea79a87458.png)

This is how his old R used to look.

https://user-images.githubusercontent.com/110841373/186273067-7ecb000b-8272-4177-b6ff-5923b3f4c694.mp4

**Comment by FlyOutBoy** [comment]
Its already full ability rework, not enchance

**Comment by tpdjairks** [comment]
Don't need to make it from scratch or exactly like the old one. The start of the animation it's ok the way it is but needs a 'continuation'. Or just reduce the delay until it looks decent. It should still have 'some' delay though.

**Comment by FlyOutBoy** [comment]
done
