### ISSUE TITLE
Bane armor & Zero Squad armor dmg return active bug

### ISSUE THREAD

**Issue by tpdjairks** [FlyOutBoy/BvO-Another#97]
![image](https://user-images.githubusercontent.com/110841373/186564383-5c34e545-43fb-4ca4-8140-d420744b58e0.png)
Using the active and then attacking the enemy will permanently stun you. 
It only happens sometimes but it's always vs the same enemies. Ikkaku and Enel for example from my tests so I believe it might have something to do with the dmg type that it returns.

**Comment by FlyOutBoy** [comment]
enemy item slots needed

**Comment by tpdjairks** [comment]
It happens when I have the active and they deal dmg to me with certain abilities it seems.
For Kuma it's probably the return dmg passive on his W, that's why I believed the bug happened when I attack the enemy while I have the active.
For Enel I believe it's the W dmg.
For Ikkaku I believe it's the Counter dmg(W-passive).
And idk, there's others as well I'm sure.

**Comment by FlyOutBoy** [comment]
![image](https://user-images.githubusercontent.com/33839947/186940607-36638e03-632a-46e6-8910-49387766ddcd.png)
for 2 tests i dont stunning ,so its done

**Comment by tpdjairks** [comment]
I'll have to test that.
